@startuml

left to right direction
:User: as User
:Server: as Server

rectangle "Funzioni Client" {
  (Creazione utente) as Creazione
  (Eliminazione utente) as Eliminazione
  (Visualizzazione utente) as Visualizzazione
}

rectangle "Funzioni Server" {
  (Approvazione Account) as Approvazione
}

User --> Creazione : Richiesta
Creazione --> Approvazione : Richiesta

Server -up-> Approvazione : Richiesta
@enduml